from pathlib import Path

path = Path(__file__).resolve().parents[1] / 'src/Hello1Drive.Core/ViewModels/MainViewModel.cs'
text = path.read_text(encoding='utf-8')

old = '''    private async Task ApplyFolderTotalCountTaskAsync(\n        Task<int?> totalCountTask,\n        string cacheKey,\n        long navigationVersion)\n    {\n        try\n        {\n            var total = await totalCountTask.ConfigureAwait(false);\n            if (total is null)\n                return;\n\n            await Dispatcher.UIThread.InvokeAsync(() =>\n            {\n                if (navigationVersion != _folderNavigationVersion || FolderCacheKey(CurrentFolderId) != cacheKey)\n                    return;\n\n                SetCurrentFolderTotalItemCount(total);\n                if (string.IsNullOrWhiteSpace(SearchText))\n                    ReconcileMobileSlotCount(Math.Max(total.Value, _allItems.Count));\n                if (_folderCache.TryGetValue(cacheKey, out var entry))\n                    entry.TotalItemCount = total;\n                ScheduleStartupSnapshotSave();\n            });\n        }\n        catch (OperationCanceledException)\n        {\n            // Navigation superseded the parallel count request.\n        }\n        catch\n        {\n            // Count metadata is optional; background enumeration still discovers the final count.\n        }\n    }\n\n    private async Task RefreshFolderTotalCountInBackgroundAsync(\n        string? folderId,\n        string cacheKey,\n        long navigationVersion)\n    {\n        try\n        {\n            var total = await TryGetFolderTotalItemCountAsync(folderId).ConfigureAwait(false);\n            if (total is null)\n                return;\n\n            await Dispatcher.UIThread.InvokeAsync(() =>\n            {\n                if (navigationVersion != _folderNavigationVersion || FolderCacheKey(CurrentFolderId) != cacheKey)\n                    return;\n\n                SetCurrentFolderTotalItemCount(total);\n                if (string.IsNullOrWhiteSpace(SearchText))\n                    ReconcileMobileSlotCount(Math.Max(total.Value, _allItems.Count));\n                if (_folderCache.TryGetValue(cacheKey, out var entry))\n                    entry.TotalItemCount = total;\n                ScheduleStartupSnapshotSave();\n            });\n        }\n        catch\n        {\n            // Item count is supplementary metadata and must never hold up folder navigation.\n        }\n    }\n'''

new = '''    private async Task ApplyFolderTotalCountTaskAsync(\n        Task<int?> totalCountTask,\n        string cacheKey,\n        long navigationVersion)\n    {\n        try\n        {\n            var total = await totalCountTask.ConfigureAwait(false);\n            if (total is null)\n                return;\n\n            await ApplyFolderTotalCountWhenIdleAsync(total.Value, cacheKey, navigationVersion).ConfigureAwait(false);\n        }\n        catch (OperationCanceledException)\n        {\n            // Navigation superseded the parallel count request.\n        }\n        catch\n        {\n            // Count metadata is optional; background enumeration still discovers the final count.\n        }\n    }\n\n    private async Task RefreshFolderTotalCountInBackgroundAsync(\n        string? folderId,\n        string cacheKey,\n        long navigationVersion)\n    {\n        try\n        {\n            var total = await TryGetFolderTotalItemCountAsync(folderId).ConfigureAwait(false);\n            if (total is null)\n                return;\n\n            await ApplyFolderTotalCountWhenIdleAsync(total.Value, cacheKey, navigationVersion).ConfigureAwait(false);\n        }\n        catch\n        {\n            // Item count is supplementary metadata and must never hold up folder navigation.\n        }\n    }\n\n    private async Task ApplyFolderTotalCountWhenIdleAsync(\n        int total,\n        string cacheKey,\n        long navigationVersion)\n    {\n        while (true)\n        {\n            // Establishing a previously unknown count can allocate thousands of fixed slots. It is\n            // supplementary metadata, so never let that collection growth land inside a desktop\n            // wheel/scrollbar gesture. Mobile native lists keep their existing immediate behavior.\n            while (!IsMobilePlatform && _desktopListScrolling)\n                await Task.Delay(24).ConfigureAwait(false);\n\n            var result = await Dispatcher.UIThread.InvokeAsync(() =>\n            {\n                if (navigationVersion != _folderNavigationVersion || FolderCacheKey(CurrentFolderId) != cacheKey)\n                    return -1;\n                if (!IsMobilePlatform && _desktopListScrolling)\n                    return 0;\n\n                SetCurrentFolderTotalItemCount(total);\n                if (string.IsNullOrWhiteSpace(SearchText))\n                    ReconcileMobileSlotCount(Math.Max(total, _allItems.Count));\n                if (_folderCache.TryGetValue(cacheKey, out var entry))\n                    entry.TotalItemCount = total;\n                ScheduleStartupSnapshotSave();\n                return 1;\n            }, DispatcherPriority.Background);\n\n            if (result != 0)\n                return;\n            await Task.Delay(24).ConfigureAwait(false);\n        }\n    }\n'''

if text.count(old) != 1:
    raise RuntimeError(f'expected total-count method block once, got {text.count(old)}')
path.write_text(text.replace(old, new, 1), encoding='utf-8')
